#!/bin/sh

[ -z $1 ] || (
docker build -t hlds:latest .
)

docker run -it --rm\
 -p 26900:26900/udp\
 -p 27020:27020/udp\
 -p 27015:27015/udp\
 -p 27015:27015\
 -e GAME="cstrike"\
 -e MAXPLAYERS="8"\
 -e START_MAP="de_dust2"\
 -e SERVER_NAME="Counter-Strike 1.6 Server"\
 -e START_MONEY="800"\
 -e BUY_TIME="0.25"\
 -e FRIENDLY_FIRE="1"\
 -e RESTART_ON_FAIL="1"\
 -e SERVER_PASSWORD="secret"\
 -e RCON_PASSWORD="supersecret"\
 hlds:latest

# --network=host\
# hlds:latest
